import * as admin from 'firebase-admin';

export const initialExercises = [
  // PERNAS
  {
    name: 'Agachamento Livre',
    description: 'Fique em pé com os pés na largura dos ombros. Flexione os joelhos descendo o quadril até formar 90°, mantendo a coluna reta e os calcanhares no chão. Retorne controlando o movimento.',
    category: 'Pernas',
    muscleGroup: ['Quadríceps', 'Glúteos', 'Core'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Agachamento no Smith',
    description: 'Posicione a barra do smith nas costas, pés um pouco à frente. Flexione os joelhos até 90° mantendo a coluna neutra e suba controlando o movimento.',
    category: 'Pernas',
    muscleGroup: ['Quadríceps', 'Glúteos', 'Isquiotibiais'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Leg Press 45°',
    description: 'Sente-se no aparelho com os pés na largura dos ombros. Flexione os joelhos controlando a descida e empurre a plataforma estendendo as pernas sem travar os joelhos.',
    category: 'Pernas',
    muscleGroup: ['Quadríceps', 'Glúteos', 'Isquiotibiais'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Afundo com Halteres',
    description: 'Dê um passo à frente segurando halteres. Flexione ambos os joelhos até 90° mantendo o tronco ereto. Retorne à posição inicial e alterne as pernas.',
    category: 'Pernas',
    muscleGroup: ['Quadríceps', 'Glúteos', 'Core'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Avanço Caminhando',
    description: 'Dê passos alternados à frente com joelhos formando 90°, mantendo o tronco ereto e contraindo as pernas a cada passada.',
    category: 'Pernas',
    muscleGroup: ['Quadríceps', 'Glúteos', 'Isquiotibiais'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Cadeira Extensora',
    description: 'Sente-se no aparelho, ajuste o rolo acima do tornozelo e estenda os joelhos até o fim. Desça lentamente controlando a volta.',
    category: 'Pernas',
    muscleGroup: ['Quadríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Mesa Flexora',
    description: 'Deite no aparelho, ajuste o rolo nos calcanhares e flexione os joelhos levando-os em direção aos glúteos. Retorne controlando o movimento.',
    category: 'Pernas',
    muscleGroup: ['Isquiotibiais'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Stiff com Barra',
    description: 'Segure a barra à frente das coxas, desça mantendo as pernas quase estendidas e a coluna neutra até sentir alongar a parte posterior das pernas. Suba contraindo glúteos.',
    category: 'Pernas',
    muscleGroup: ['Isquiotibiais', 'Glúteos', 'Eretores da espinha'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Elevação de Quadril com Barra',
    description: 'Deite no chão com as costas apoiadas em um banco, coloque a barra no quadril e empurre para cima contraindo glúteos no topo.',
    category: 'Pernas',
    muscleGroup: ['Glúteos', 'Isquiotibiais', 'Core'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Glúteo 4 Apoios no Cabo',
    description: 'Ajuste a caneleira no cabo, apoie mãos e joelhos no banco e empurre a perna para trás até a extensão completa, contraindo glúteo.',
    category: 'Pernas',
    muscleGroup: ['Glúteos'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Panturrilha em Pé',
    description: 'Suba na ponta dos pés mantendo o corpo ereto e desça lentamente. Pode ser feito no aparelho ou com peso livre.',
    category: 'Pernas',
    muscleGroup: ['Panturrilha'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Panturrilha Sentado',
    description: 'Sentado no aparelho, apoie os pés na plataforma e eleve os calcanhares contraindo a panturrilha no topo.',
    category: 'Pernas',
    muscleGroup: ['Panturrilha'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // PEITO
  {
    name: 'Supino Reto com Barra',
    description: 'Deite no banco, segure a barra com pegada média e desça até o peito. Empurre de volta mantendo o controle e contraindo o peitoral.',
    category: 'Peito',
    muscleGroup: ['Peitoral', 'Tríceps', 'Deltoides anteriores'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Supino Inclinado com Halteres',
    description: 'Deite no banco inclinado, segure os halteres e empurre para cima. Desça lentamente mantendo o controle do movimento.',
    category: 'Peito',
    muscleGroup: ['Peitoral Superior', 'Tríceps', 'Deltoides anteriores'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Supino Declinado com Barra',
    description: 'Deite no banco declinado, segure a barra e desça até o peito inferior. Empurre para cima controlando a descida.',
    category: 'Peito',
    muscleGroup: ['Peitoral Inferior', 'Tríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Crucifixo Reto com Halteres',
    description: 'Deite no banco com halteres, braços semi-flexionados. Abra lateralmente até alinhar com o peito e retorne juntando os halteres.',
    category: 'Peito',
    muscleGroup: ['Peitoral'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Crossover no Cabo',
    description: 'Em pé entre os cabos, puxe as manoplas à frente do corpo cruzando levemente no final e contraia o peitoral.',
    category: 'Peito',
    muscleGroup: ['Peitoral'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Flexão de Braço Tradicional',
    description: 'Com mãos no chão na largura dos ombros, mantenha o corpo reto e desça até próximo ao peito. Empurre de volta controlando.',
    category: 'Peito',
    muscleGroup: ['Peitoral', 'Tríceps', 'Deltoides anteriores'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // COSTAS
  {
    name: 'Puxada Aberta na Barra',
    description: 'Segure a barra com pegada aberta e puxe em direção ao peito, mantendo a coluna ereta e contraindo as costas no final.',
    category: 'Costas',
    muscleGroup: ['Dorsal', 'Trapézio', 'Bíceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Puxada Fechada Supinada',
    description: 'Segure a barra com pegada invertida fechada e puxe até o peito. Contraia as escápulas no final do movimento.',
    category: 'Costas',
    muscleGroup: ['Dorsal', 'Bíceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Remada Curvada com Barra',
    description: 'Incline o tronco, mantenha a coluna neutra e puxe a barra em direção ao abdômen, contraindo as costas.',
    category: 'Costas',
    muscleGroup: ['Dorsal', 'Trapézio', 'Romboides', 'Bíceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Remada Unilateral com Halter',
    description: 'Apoie uma mão no banco, mantenha a coluna reta e puxe o halter para cima contraindo as costas.',
    category: 'Costas',
    muscleGroup: ['Dorsal', 'Trapézio', 'Bíceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Levantamento Terra Convencional',
    description: 'Com a barra no chão, pés afastados, segure a barra e suba mantendo a coluna neutra até a posição ereta.',
    category: 'Costas',
    muscleGroup: ['Dorsal', 'Glúteos', 'Quadríceps', 'Eretores da espinha'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Puxada na Frente com Corda',
    description: 'No pulley alto, use a corda e puxe em direção ao rosto abrindo os cotovelos e contraindo as escápulas.',
    category: 'Costas',
    muscleGroup: ['Trapézio', 'Deltoides posteriores', 'Romboides'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // OMBROS
  {
    name: 'Desenvolvimento com Barra',
    description: 'Com a barra na altura dos ombros, empurre acima da cabeça até estender os braços. Mantenha a postura ereta.',
    category: 'Ombros',
    muscleGroup: ['Deltoides', 'Tríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Desenvolvimento com Halteres',
    description: 'Segure halteres na altura dos ombros e empurre para cima até a extensão completa dos braços.',
    category: 'Ombros',
    muscleGroup: ['Deltoides', 'Tríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Elevação Lateral com Halteres',
    description: 'Em pé, eleve os halteres lateralmente até a altura dos ombros mantendo cotovelos levemente flexionados.',
    category: 'Ombros',
    muscleGroup: ['Deltoides Laterais'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Elevação Frontal com Halteres',
    description: 'Levante os halteres à frente até a altura dos ombros controlando a descida.',
    category: 'Ombros',
    muscleGroup: ['Deltoides Anteriores'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Crucifixo Invertido no Banco',
    description: 'Deite de bruços no banco inclinado e abra os halteres lateralmente contraindo as costas e deltoides posteriores.',
    category: 'Ombros',
    muscleGroup: ['Deltoides Posteriores', 'Trapézio'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // BRAÇOS
  {
    name: 'Rosca Direta com Barra',
    description: 'Em pé, segure a barra em supinação e flexione os cotovelos levando a barra até próximo aos ombros.',
    category: 'Braços',
    muscleGroup: ['Bíceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Rosca Alternada com Halteres',
    description: 'Em pé, flexione alternadamente cada braço mantendo o cotovelo fixo ao lado do corpo.',
    category: 'Braços',
    muscleGroup: ['Bíceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Rosca Martelo',
    description: 'Segure os halteres em posição neutra (polegares para cima) e flexione os cotovelos alternadamente.',
    category: 'Braços',
    muscleGroup: ['Bíceps', 'Braquial'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Tríceps Testa com Barra',
    description: 'Deitado no banco, flexione os cotovelos levando a barra em direção à testa e estenda novamente.',
    category: 'Braços',
    muscleGroup: ['Tríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Tríceps Corda no Pulley',
    description: 'No pulley alto, puxe a corda para baixo estendendo os cotovelos e abrindo no final para máxima contração.',
    category: 'Braços',
    muscleGroup: ['Tríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // ABDÔMEN
  {
    name: 'Abdominal Reto no Solo',
    description: 'Deite de costas, mãos na cabeça e eleve o tronco contraindo o abdômen sem forçar o pescoço.',
    category: 'Abdômen',
    muscleGroup: ['Reto Abdominal'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Abdominal Oblíquo',
    description: 'Deite de lado ou faça movimento cruzado levando o cotovelo em direção ao joelho oposto, contraindo oblíquos.',
    category: 'Abdômen',
    muscleGroup: ['Oblíquos'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Elevação de Pernas no Solo',
    description: 'Deite e levante as pernas até 90°, mantendo o abdômen contraído e controlando a descida.',
    category: 'Abdômen',
    muscleGroup: ['Infra Abdominal'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Prancha Isométrica',
    description: 'Apoie antebraços e pontas dos pés no chão mantendo o corpo reto e o abdômen contraído o tempo todo.',
    category: 'Abdômen',
    muscleGroup: ['Core', 'Reto Abdominal'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Abdominal Bicicleta',
    description: 'Deite no chão e simule pedalar levando o cotovelo ao joelho oposto alternadamente, contraindo oblíquos e reto abdominal.',
    category: 'Abdômen',
    muscleGroup: ['Reto Abdominal', 'Oblíquos'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // CARDIO
  {
    name: 'Corrida na Esteira',
    description: 'Ajuste a velocidade e incline levemente o tronco mantendo a postura ereta durante a corrida.',
    category: 'Cardio',
    muscleGroup: ['Cardiorrespiratório', 'Pernas'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Bicicleta Ergométrica',
    description: 'Ajuste o banco e pedale mantendo cadência constante e postura ereta.',
    category: 'Cardio',
    muscleGroup: ['Cardiorrespiratório', 'Pernas'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Elíptico',
    description: 'Movimente braços e pernas simultaneamente mantendo ritmo constante e postura ereta.',
    category: 'Cardio',
    muscleGroup: ['Cardiorrespiratório', 'Pernas', 'Braços'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Escada',
    description: 'Suba os degraus mantendo o tronco ereto e ritmo constante, trabalhando pernas e cardio ao mesmo tempo.',
    category: 'Cardio',
    muscleGroup: ['Quadríceps', 'Glúteos', 'Cardiorrespiratório'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
    // PERNAS - variações e complementos
  {
    name: 'Agachamento Sumô com Halteres',
    description: 'Posicione os pés afastados, segure um halter entre as pernas e agache mantendo a coluna reta. Retorne controlando o movimento.',
    category: 'Pernas',
    muscleGroup: ['Adutores', 'Glúteos', 'Quadríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Pistol Squat (Agachamento Unilateral)',
    description: 'Agache em uma perna estendida para frente, mantendo equilíbrio e controle no movimento.',
    category: 'Pernas',
    muscleGroup: ['Quadríceps', 'Glúteos', 'Core'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Elevação de Quadril Unilateral',
    description: 'Deite de costas, apoie um pé no chão e eleve o quadril contraindo o glúteo da perna apoiada.',
    category: 'Pernas',
    muscleGroup: ['Glúteos', 'Isquiotibiais', 'Core'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Step-up com Halteres',
    description: 'Suba em um banco ou plataforma com um pé, empurre o corpo para cima e desça controlando o movimento.',
    category: 'Pernas',
    muscleGroup: ['Quadríceps', 'Glúteos', 'Isquiotibiais'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // PEITO - variações
  {
    name: 'Flexão de Braço com Pés Elevados',
    description: 'Realize flexões com os pés apoiados em um banco, aumentando a ativação do peitoral superior.',
    category: 'Peito',
    muscleGroup: ['Peitoral Superior', 'Tríceps', 'Deltoides anteriores'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Supino com Pegada Fechada',
    description: 'No banco, segure a barra com pegada mais próxima, focando em tríceps e peitoral interno.',
    category: 'Peito',
    muscleGroup: ['Peitoral', 'Tríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // COSTAS - variações
  {
    name: 'Pullover com Halteres',
    description: 'Deite no banco segurando um halter acima do peito e abaixe atrás da cabeça mantendo os braços levemente flexionados.',
    category: 'Costas',
    muscleGroup: ['Dorsal', 'Peitoral'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Remada Cavalinho',
    description: 'Segure a barra com pegada pronada, incline o tronco e puxe a barra na direção do abdômen.',
    category: 'Costas',
    muscleGroup: ['Dorsal', 'Trapézio', 'Bíceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // OMBROS - variações
  {
    name: 'Face Pull no Cabo',
    description: 'Puxe a corda do cabo em direção ao rosto com cotovelos abertos para ativar deltoides posteriores.',
    category: 'Ombros',
    muscleGroup: ['Deltoides posteriores', 'Trapézio'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Elevação Lateral no Cabo',
    description: 'Puxe o cabo lateralmente até a altura do ombro mantendo o tronco ereto e o cotovelo levemente flexionado.',
    category: 'Ombros',
    muscleGroup: ['Deltoides laterais'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // BRAÇOS - variações
  {
    name: 'Tríceps Francês com Halteres',
    description: 'Sentado ou em pé, flexione os cotovelos levando o halter atrás da cabeça e estenda os braços.',
    category: 'Braços',
    muscleGroup: ['Tríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Rosca Concentrada',
    description: 'Sentado, apoie o cotovelo na coxa e flexione o braço levantando o halter até o ombro.',
    category: 'Braços',
    muscleGroup: ['Bíceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // ABDÔMEN - variações
  {
    name: 'Prancha Lateral',
    description: 'Apoie um antebraço e a lateral do pé no chão, mantendo o corpo reto e o abdômen contraído.',
    category: 'Abdômen',
    muscleGroup: ['Oblíquos', 'Core'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Elevação de Pernas na Barra Fixa',
    description: 'Pendure na barra fixa e eleve as pernas estendidas até formar 90° com o tronco.',
    category: 'Abdômen',
    muscleGroup: ['Infra abdominal', 'Core'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // CARDIO - variações
  {
    name: 'Burpee',
    description: 'Combine agachamento, salto e flexão em sequência rápida para treino cardiovascular intenso.',
    category: 'Cardio',
    muscleGroup: ['Cardiorrespiratório', 'Pernas', 'Peito', 'Braços'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Jumping Jack',
    description: 'Salte abrindo pernas e braços simultaneamente e retorne à posição inicial, mantendo ritmo acelerado.',
    category: 'Cardio',
    muscleGroup: ['Cardiorrespiratório', 'Pernas', 'Braços'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // FUNCIONAL / MOBILIDADE
  {
    name: 'Kettlebell Swing',
    description: 'Balance o kettlebell entre as pernas e para frente com força do quadril, mantendo a coluna neutra.',
    category: 'Funcional',
    muscleGroup: ['Glúteos', 'Isquiotibiais', 'Core'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Flexão Spiderman',
    description: 'Durante a flexão, leve um joelho lateralmente em direção ao cotovelo, ativando abdômen e flexores de quadril.',
    category: 'Funcional',
    muscleGroup: ['Peitoral', 'Core', 'Quadríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Agachamento com Salto',
    description: 'Faça um agachamento normal e exploda para cima em um salto, aterrissando suavemente.',
    category: 'Funcional',
    muscleGroup: ['Quadríceps', 'Glúteos', 'Cardiorrespiratório'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Prancha com Toque no Ombro',
    description: 'Em posição de prancha alta, toque alternadamente cada ombro com a mão oposta mantendo o corpo estável.',
    category: 'Funcional',
    muscleGroup: ['Core', 'Ombros'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },

  // ALONGAMENTO
  {
    name: 'Alongamento de Isquiotibiais em Pé',
    description: 'Com as pernas retas, incline o tronco à frente tentando alcançar os pés sem dobrar os joelhos.',
    category: 'Alongamento',
    muscleGroup: ['Isquiotibiais'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Alongamento de Peitoral na Parede',
    description: 'Com o braço aberto e apoiado na parede, gire o tronco para o lado oposto para alongar o peitoral.',
    category: 'Alongamento',
    muscleGroup: ['Peitoral'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Alongamento de Quadríceps em Pé',
    description: 'Apoie-se e puxe o pé em direção ao glúteo para alongar a parte frontal da coxa.',
    category: 'Alongamento',
    muscleGroup: ['Quadríceps'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
  {
    name: 'Alongamento de Ombros Cruzado',
    description: 'Leve um braço cruzado sobre o peito e pressione com o outro para alongar os ombros.',
    category: 'Alongamento',
    muscleGroup: ['Ombros'],
    images: [],
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: '',
    deletedAt: '',
  },
];
